/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TowingRouteImport } from './routes/towing'
import { Route as PoliceRouteImport } from './routes/police'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const TowingRoute = TowingRouteImport.update({
  id: '/towing',
  path: '/towing',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliceRoute = PoliceRouteImport.update({
  id: '/police',
  path: '/police',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/chat': typeof ChatRoute
  '/contacts': typeof ContactsRoute
  '/hospitals': typeof HospitalsRoute
  '/police': typeof PoliceRoute
  '/towing': typeof TowingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/chat': typeof ChatRoute
  '/contacts': typeof ContactsRoute
  '/hospitals': typeof HospitalsRoute
  '/police': typeof PoliceRoute
  '/towing': typeof TowingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/chat': typeof ChatRoute
  '/contacts': typeof ContactsRoute
  '/hospitals': typeof HospitalsRoute
  '/police': typeof PoliceRoute
  '/towing': typeof TowingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/chat'
    | '/contacts'
    | '/hospitals'
    | '/police'
    | '/towing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/chat'
    | '/contacts'
    | '/hospitals'
    | '/police'
    | '/towing'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/chat'
    | '/contacts'
    | '/hospitals'
    | '/police'
    | '/towing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ChatRoute: typeof ChatRoute
  ContactsRoute: typeof ContactsRoute
  HospitalsRoute: typeof HospitalsRoute
  PoliceRoute: typeof PoliceRoute
  TowingRoute: typeof TowingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/towing': {
      id: '/towing'
      path: '/towing'
      fullPath: '/towing'
      preLoaderRoute: typeof TowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/police': {
      id: '/police'
      path: '/police'
      fullPath: '/police'
      preLoaderRoute: typeof PoliceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ChatRoute: ChatRoute,
  ContactsRoute: ContactsRoute,
  HospitalsRoute: HospitalsRoute,
  PoliceRoute: PoliceRoute,
  TowingRoute: TowingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
